server:
  port: 17001
spring :
  dubbo :
    application: provider
    registry:
      address: zookeeper://localhost:2181
    protocol:
       name: dubbo
       port: 20880
    scan: demo.chk.provider.service